(function(){
'use strict';
const FEED='1dePuxVQBhOFCynpRmVDcxnHi5aoR-UtwZWwn2Y7GkDs';
const BUILD='V4-20260820-1445';
const $=id=>document.getElementById(id);
const nf=new Intl.NumberFormat('vi-VN');
const pf=v=>new Intl.NumberFormat('vi-VN',{style:'percent',maximumFractionDigits:1}).format(Number.isFinite(v)?v:0);
const state={rows:[],scopeRows:[],companies:[],provinces:[],recruitments:[],hotspots:[],dates:[],live:false,dailyAvailable:false,refreshing:false,lastRefresh:0};
const FALLBACK={companies:[['Dương Huy',73,55,18,13],['Hà Lầm',73,52,21,0],['Hạ Long',128,106,22,58],['Hòn Gai',134,121,13,0],['Khe Chàm',208,155,53,0],['Mạo Khê',64,52,12,0],['Mông Dương',75,54,21,0],['Nam Mẫu',116,92,24,0],['Núi Béo',110,82,28,0],['Quang Hanh',53,40,13,7],['Sin Quyền',97,96,1,0],['Thống Nhất',58,29,29,43],['Uông Bí',47,42,5,0],['Vàng Danh',166,139,27,0],['Xây Lắp Mỏ',30,8,22,12]].map(([name,total,active,drop,grad])=>({name,total,active,drop,grad,dropRate:total?drop/total:0,activeRate:total?active/total:0}))};
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){if(typeof v==='number'&&Number.isFinite(v))return v;const n=Number(String(v??'').replace(/,/g,'').replace('%','').trim());return Number.isFinite(n)?n:0}
function statusOf(v){const n=norm(v);if(n==='dang thuc tap'||n==='dang tt')return'active';if(n==='bo'||n==='bo hoc'||n==='bo ttsx')return'dropped';if(n.includes('tot nghiep'))return'graduated';return'other'}
function isUnknown(v){const n=norm(v);return !n||n.includes('chua ro')}
function cell(c){return c?.f??c?.v??''}
function setSync(cls,text){const el=$('sync');if(!el)return;el.className='sync '+cls;const s=el.querySelector('span:last-child');if(s)s.textContent=text}
function metrics(rows){let active=0,drop=0,grad=0,other=0;for(const r of rows){if(r.status==='active')active++;else if(r.status==='dropped')drop++;else if(r.status==='graduated')grad++;else other++}const total=active+drop;return{total,active,drop,grad,other,dropRate:total?drop/total:0,activeRate:total?active/total:0}}
function summaryMetrics(a){const m=a.reduce((s,x)=>({total:s.total+x.total,active:s.active+x.active,drop:s.drop+x.drop,grad:s.grad+x.grad}),{total:0,active:0,drop:0,grad:0});return{...m,other:0,dropRate:m.total?m.drop/m.total:0,activeRate:m.total?m.active/m.total:0}}
function group(rows,key){const m=new Map;for(const r of rows){const k=r[key]||'Chưa rõ';if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return[...m.entries()]}
function gviz(sheet,range,headers=1,timeout=30000){return new Promise((resolve,reject)=>{const cb='__v4_'+Date.now()+'_'+Math.random().toString(36).slice(2),id='s_'+cb;let done=false;const timer=setTimeout(()=>finish(new Error('Quá thời gian tải '+sheet)),timeout);function finish(err,data){if(done)return;done=true;clearTimeout(timer);delete window[cb];document.getElementById(id)?.remove();err?reject(err):resolve(data)}window[cb]=resp=>{if(resp?.status!=='ok'||!resp.table)return finish(new Error(resp?.errors?.[0]?.detailed_message||'Không đọc được '+sheet));finish(null,resp.table)};const s=document.createElement('script');s.id=id;s.src=`https://docs.google.com/spreadsheets/d/${FEED}/gviz/tq?sheet=${encodeURIComponent(sheet)}&range=${encodeURIComponent(range)}&headers=${headers}&tqx=${encodeURIComponent('out:json;responseHandler:'+cb)}&_=${Date.now()}`;s.onerror=()=>finish(new Error('Không tải được '+sheet));document.head.appendChild(s)})}
function parseCore(t){return t.rows.map(row=>{const c=row.c||[];const r={id:String(cell(c[0])).trim(),company:String(cell(c[1])).trim(),province:String(cell(c[2])).trim(),campus:String(cell(c[3])).trim(),recruitment:String(cell(c[4])).trim(),unit:String(cell(c[5])).trim(),statusRaw:String(cell(c[6])).trim(),daily:{}};r.status=statusOf(r.statusRaw);return r}).filter(r=>r.company)}
function parseCompanies(t){return t.rows.map(row=>{const c=row.c||[],name=String(cell(c[0])).trim();if(!name||norm(name)==='doanh nghiep'||norm(name)==='tong cong')return null;const total=num(cell(c[1])),active=num(cell(c[2])),drop=num(cell(c[3])),grad=num(cell(c[4]));return{name,total,active,drop,grad,dropRate:total?drop/total:0,activeRate:total?active/total:0}}).filter(Boolean)}
function parseSimple(t){return t.rows.map(row=>{const c=row.c||[],name=String(cell(c[0])).trim();if(!name||norm(name)==='tinh'||norm(name)==='don vi tuyen'||norm(name)==='tong cong')return null;const total=num(cell(c[1])),active=num(cell(c[2])),drop=num(cell(c[3]));return{name,total,active,drop,dropRate:total?drop/total:0,activeRate:total?active/total:0}}).filter(Boolean)}
function parseHotspots(t){return t.rows.map(row=>{const c=row.c||[],company=String(cell(c[0])).trim(),detail=String(cell(c[2])).trim();if(!company||norm(company)==='doanh nghiep'||!detail)return null;const units=detail.split(';').map(x=>x.trim()).map(x=>{const m=x.match(/^(.*?):\s*(\d+)\s*HS/i);return m?{unit:m[1].trim(),count:Number(m[2])}:null}).filter(x=>x&&x.count>=3);return units.length?{company,total:units.reduce((s,x)=>s+x.count,0),units:units.sort((a,b)=>b.count-a.count||a.unit.localeCompare(b.unit,'vi'))}:null}).filter(Boolean)}
async function attachDaily(rows){try{const t=await gviz('_WEB_DATA','A1:AW2000',1,30000);const headers=t.cols.map((c,i)=>c.label||c.id||('C'+i)),dates=headers.slice(7),byId=new Map(rows.map(r=>[r.id,r]));for(const row of t.rows){const c=row.c||[],id=String(cell(c[0])).trim(),r=byId.get(id);if(!r)continue;for(let i=7;i<headers.length;i++)r.daily[headers[i]]=cell(c[i])}state.dates=dates;state.dailyAvailable=rows.some(r=>dates.some(d=>String(r.daily[d]??'').trim()!==''))}catch(e){console.warn('Daily optional feed unavailable',e);state.dates=[];state.dailyAvailable=false}}
function deriveCompanies(rows){return group(rows,'company').map(([name,a])=>({name,...metrics(a)}))}
function deriveSimple(rows,key){return group(rows,key).map(([name,a])=>({name,...metrics(a)}))}
function deriveRecruit(rows){return deriveSimple(rows.filter(r=>r.recruitment),'recruitment')}
function currentFilters(){return{company:$('company')?.value||'',province:$('province')?.value||'',campus:$('campus')?.value||'',recruitment:$('recruitment')?.value||'',unit:$('unit')?.value||''}}
function unfiltered(){return Object.values(currentFilters()).every(v=>!v)}
function fillSelect(id,vals){const s=$(id);if(!s)return;const cur=s.value,u=[...new Set(vals.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'vi'));s.innerHTML='<option value="">Tất cả</option>'+u.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if([...s.options].some(o=>o.value===cur))s.value=cur}
function renderKpis(m){[['kTotal',m.total],['kActive',m.active],['kDrop',m.drop],['kGrad',m.grad]].forEach(([id,v])=>{if($(id))$(id).textContent=nf.format(v)});if($('kDropRate'))$('kDropRate').textContent=pf(m.dropRate);if($('kDropRateSub'))$('kDropRateSub').textContent=pf(m.dropRate);if($('kActiveRate'))$('kActiveRate').textContent=pf(m.activeRate);if($('kActivePct'))$('kActivePct').textContent=pf(m.activeRate)}
function bars(el,arr,getVal,getName,getLabel,limit=15,red=false){if(!el)return;const a=arr.slice(0,limit),mx=Math.max(1,...a.map(getVal));el.innerHTML=a.length?a.map(x=>{const v=getVal(x),n=getName(x);return `<div class="bar-row"><div class="bar-name" title="${esc(n)}">${esc(n)}</div><div class="track"><div class="fill${red?' red':''}" style="width:${v?Math.max(1,v/mx*100):0}%"></div></div><div class="bar-value">${getLabel(x)}</div></div>`}).join(''):'<div class="notice">Không có dữ liệu.</div>'}
function rateBars(el,arr){if(!el)return;el.innerHTML=arr.slice(0,15).map(x=>{const p=Math.max(0,Math.min(100,x.dropRate*100));return `<div class="bar-row"><div class="bar-name">${esc(x.name)}</div><div class="track"><div class="fill red" style="width:${p}%"></div></div><div class="bar-value">${pf(x.dropRate)}</div></div>`}).join('')}
function ensureExtras(){if($('statusStructure'))return;const first=document.querySelector('.section.grid2');if(!first)return;const style=document.createElement('style');style.textContent='.dual-row{display:grid;grid-template-columns:minmax(125px,190px) 1fr 104px;gap:12px;align-items:center;font-size:13px}.dual-track{height:14px;display:flex;background:#eaf0f4;border-radius:999px;overflow:hidden}.dual-active{background:#16845b;height:100%}.dual-drop{background:#d64545;height:100%}.dual-value{text-align:right;font-weight:800}.status-row{display:grid;grid-template-columns:150px 1fr 96px;gap:12px;align-items:center;margin:12px 0}.status-track{height:14px;background:#eaf0f4;border-radius:999px;overflow:hidden}.status-fill{height:100%}.status-active{background:#16845b}.status-drop{background:#d64545}.status-grad{background:#d59a24}@media(max-width:720px){.dual-row{grid-template-columns:100px 1fr 90px}.status-row{grid-template-columns:100px 1fr 82px}}';document.head.appendChild(style);const s1=document.createElement('section');s1.className='section grid2 dashboard-extra';s1.innerHTML='<div class="panel"><h3>Cơ cấu tình trạng học sinh</h3><div id="statusStructure"></div></div><div class="panel"><h3>Đang thực tập / Bỏ theo doanh nghiệp</h3><div id="activeDropBars" class="bars"></div></div>';const s2=document.createElement('section');s2.className='section grid2 dashboard-extra';s2.innerHTML='<div class="panel"><h3>Top đơn vị tuyển theo HS đi TTSX</h3><div id="recruitBars" class="bars"></div></div><div class="panel"><h3>Top doanh nghiệp có HS bỏ nhiều</h3><div id="dropCountBars" class="bars"></div></div>';first.insertAdjacentElement('afterend',s2);first.insertAdjacentElement('afterend',s1)}
function renderExtras(companies,m,recruits){ensureExtras();if($('statusStructure')){const all=m.active+m.drop+m.grad+(m.other||0);$('statusStructure').innerHTML=[['Đang thực tập',m.active,'status-active'],['Bỏ TTSX',m.drop,'status-drop'],['Đã tốt nghiệp',m.grad,'status-grad']].map(([l,v,c])=>`<div class="status-row"><div><b>${l}</b></div><div class="status-track"><div class="status-fill ${c}" style="width:${all?v/all*100:0}%"></div></div><div><b>${nf.format(v)}</b> · ${pf(all?v/all:0)}</div></div>`).join('')}if($('activeDropBars')){$('activeDropBars').innerHTML=companies.slice().sort((a,b)=>b.total-a.total).map(x=>`<div class="dual-row"><div class="bar-name">${esc(x.name)}</div><div class="dual-track"><div class="dual-active" style="width:${x.total?x.active/x.total*100:0}%"></div><div class="dual-drop" style="width:${x.total?x.drop/x.total*100:0}%"></div></div><div class="dual-value">${x.active} / ${x.drop}</div></div>`).join('')}bars($('recruitBars'),recruits.slice().sort((a,b)=>b.total-a.total),x=>x.total,x=>x.name,x=>nf.format(x.total),12);bars($('dropCountBars'),companies.slice().sort((a,b)=>b.drop-a.drop),x=>x.drop,x=>x.name,x=>nf.format(x.drop),12,true)}
function rawHotspots(rows){const map=new Map;for(const r of rows.filter(r=>r.status==='dropped'&&r.company&&r.unit&&!isUnknown(r.unit))){const k=norm(r.company)+'\0'+norm(r.unit);if(!map.has(k))map.set(k,{company:r.company,unit:r.unit,count:0});map.get(k).count++}const cm=new Map;for(const x of [...map.values()].filter(x=>x.count>=3)){const k=norm(x.company);if(!cm.has(k))cm.set(k,{company:x.company,total:0,units:[]});const g=cm.get(k);g.total+=x.count;g.units.push({unit:x.unit,count:x.count})}return [...cm.values()].map(g=>({...g,units:g.units.sort((a,b)=>b.count-a.count)})).sort((a,b)=>b.total-a.total)}
function renderHotspots(){const groups=unfiltered()?state.hotspots:rawHotspots(state.scopeRows),el=$('hotspots');if(!el)return;el.innerHTML=groups.length?groups.map(g=>`<div class="hot-company-row"><div class="hot-company-box"><strong>${esc(g.company)}</strong><span>${nf.format(g.total)} HS bỏ tại ${g.units.length} công trường cảnh báo</span></div><div class="hot-unit-list">${g.units.map(u=>`<div class="hot-unit"><span>${esc(u.unit)}</span><b>${u.count} HS bỏ</b></div>`).join('')}</div></div>`).join(''):'<div class="notice ok">Không có công trường nào đạt ngưỡng ≥3 HS bỏ.</div>'}
function classify(v){if(typeof v==='number'&&Number.isFinite(v))return'score';const s=String(v??'').trim();if(!s)return'blank';if(Number.isFinite(Number(s.replace(',','.'))))return'score';if(s.toUpperCase()==='Ô')return'sick';if(s.toUpperCase()==='N')return'leave';if(s.toUpperCase()==='KLD')return'kld';return'other'}
function renderDaily(){const sec=$('dailySection'),cov=$('coveragePanel');if(!state.dailyAvailable){if(sec)sec.style.display='none';if(cov)cov.style.display='none';return}if(sec)sec.style.display='';if(cov)cov.style.display='';const day=$('day')?.value;if(!day)return;const rows=state.scopeRows.filter(r=>r.status==='active'&&norm(r.company)!=='sin quyen');let score=0,sick=0,leave=0,kld=0,other=0;for(const r of rows){const t=classify(r.daily[day]);if(t==='score')score++;else if(t==='sick')sick++;else if(t==='leave')leave++;else if(t==='kld')kld++;else if(t==='other')other++}const entered=score+sick+leave+kld+other,missing=Math.max(0,rows.length-entered);[['dExpected',rows.length],['dEntered',entered],['dScore',score],['dSick',sick],['dLeave',leave],['dKld',kld],['dMissing',missing]].forEach(([id,v])=>{if($(id))$(id).textContent=nf.format(v)});const cv=group(rows,'company').map(([name,a])=>{const e=a.filter(r=>classify(r.daily[day])!=='blank').length;return{name,expected:a.length,entered:e,rate:a.length?e/a.length:0}}).sort((a,b)=>b.rate-a.rate);if($('coverage'))$('coverage').innerHTML=cv.map(x=>`<div class="bar-row"><div class="bar-name">${esc(x.name)}</div><div class="track"><div class="fill" style="width:${x.rate*100}%"></div></div><div class="bar-value">${pf(x.rate)}</div></div>`).join('')}
function render(){const f=currentFilters();state.scopeRows=state.rows.filter(r=>Object.entries(f).every(([k,v])=>!v||r[k]===v));const uf=unfiltered(),companies=uf?state.companies:deriveCompanies(state.scopeRows),provinces=uf?state.provinces:deriveSimple(state.scopeRows,'province'),recruits=uf?state.recruitments:deriveRecruit(state.scopeRows),m=uf?summaryMetrics(state.companies):metrics(state.scopeRows);renderKpis(m);bars($('companyBars'),companies.slice().sort((a,b)=>b.total-a.total),x=>x.total,x=>x.name,x=>nf.format(x.total));rateBars($('dropBars'),companies.slice().sort((a,b)=>b.dropRate-a.dropRate));if($('companyTable'))$('companyTable').innerHTML=companies.slice().sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(x=>`<tr><td>${esc(x.name)}</td><td>${nf.format(x.total)}</td><td>${nf.format(x.active)}</td><td>${nf.format(x.drop)}</td><td>${pf(x.dropRate)}</td></tr>`).join('');bars($('provinceBars'),provinces.filter(x=>norm(x.name)!=='chua ro tinh').slice().sort((a,b)=>b.total-a.total),x=>x.total,x=>x.name,x=>nf.format(x.total),12);const q=[[state.scopeRows.filter(r=>isUnknown(r.province)).length,'Chưa rõ tỉnh'],[state.scopeRows.filter(r=>isUnknown(r.campus)).length,'Thiếu/chưa rõ phân hiệu'],[state.scopeRows.filter(r=>isUnknown(r.recruitment)).length,'Thiếu/chưa rõ đơn vị tuyển'],[state.scopeRows.filter(r=>isUnknown(r.unit)).length,'Thiếu/chưa rõ công trường']];if($('quality'))$('quality').innerHTML=q.map(([v,l])=>`<div class="q"><strong>${nf.format(v)}</strong><span>${l}</span></div>`).join('');if($('scope'))$('scope').textContent=uf?'Toàn bộ dữ liệu':`${nf.format(state.scopeRows.length)} bản ghi · ${nf.format(m.total)} HS đi TTSX trong phạm vi lọc`;renderExtras(companies,m,recruits);renderHotspots();renderDaily()}
function validate(){if(state.rows.length!==1565)throw new Error(`Feed lõi thiếu dòng ${state.rows.length}/1565`);const names=new Set(state.rows.map(r=>norm(r.company)));if(names.size!==15)throw new Error(`Feed lõi thiếu doanh nghiệp ${names.size}/15`);const raw=new Map(deriveCompanies(state.rows).map(x=>[norm(x.name),x]));for(const s of state.companies){const r=raw.get(norm(s.name));if(!r||r.total!==s.total||r.active!==s.active||r.drop!==s.drop||r.grad!==s.grad)throw new Error(`${s.name}: raw ${r?`${r.total}/${r.active}/${r.drop}/${r.grad}`:'thiếu'} ≠ chuẩn ${s.total}/${s.active}/${s.drop}/${s.grad}`)}}
async function refresh(){if(state.refreshing)return;state.refreshing=true;setSync('','Đang kết nối feed V4');if($('notice')){$('notice').className='notice';$('notice').textContent='Đang nạp feed lõi ẩn danh V4...'}try{const [coreT,compT,provT,recT,hotT]=await Promise.all([gviz('_WEB_CORE','A1:G2000'),gviz('TK theo doanh nghiệp','A4:F20'),gviz('TK theo tỉnh','A4:E100'),gviz('TK theo đơn vị TS','A4:E60'),gviz('TK theo doanh nghiệp','A24:F40')]);state.rows=parseCore(coreT);state.companies=parseCompanies(compT);state.provinces=parseSimple(provT);state.recruitments=parseSimple(recT);state.hotspots=parseHotspots(hotT);validate();await attachDaily(state.rows);state.live=true;state.lastRefresh=Date.now();fillSelect('company',state.rows.map(r=>r.company));fillSelect('province',state.rows.map(r=>r.province));fillSelect('campus',state.rows.map(r=>r.campus));fillSelect('recruitment',state.rows.map(r=>r.recruitment));fillSelect('unit',state.rows.map(r=>r.unit));if($('day')){if(state.dates.length){$('day').innerHTML=state.dates.map(d=>`<option>${esc(d)}</option>`).join('');const today=new Date().toLocaleDateString('vi-VN');if(state.dates.includes(today))$('day').value=today}else $('day').innerHTML='<option>Chưa có dữ liệu ngày</option>'}render();setSync('ok','Feed public · V4 trực tiếp');if($('notice')){$('notice').className='notice ok';$('notice').textContent=`Dữ liệu trực tiếp đã đối soát: 1.432 HS = 1.123 đang TT + 309 bỏ; 133 tốt nghiệp; 15/15 doanh nghiệp. Build ${BUILD}.`}if($('updated'))$('updated').textContent='Đồng bộ '+new Date().toLocaleString('vi-VN',{hour12:false})}catch(e){console.error(e);state.live=false;state.companies=FALLBACK.companies;renderKpis(summaryMetrics(FALLBACK.companies));setSync('err','Feed V4 lỗi');if($('notice')){$('notice').className='notice err';$('notice').textContent='Feed V4 chưa đạt: '+e.message+`. Build ${BUILD}.`}}finally{state.refreshing=false}}
['company','province','campus','recruitment','unit'].forEach(id=>$(id)?.addEventListener('change',render));$('day')?.addEventListener('change',renderDaily);$('clear')?.addEventListener('click',()=>{['company','province','campus','recruitment','unit'].forEach(id=>{if($(id))$(id).value=''});render()});$('refresh')?.addEventListener('click',refresh);setInterval(()=>{if(document.visibilityState==='visible')refresh()},300000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-state.lastRefresh>60000)refresh()});window.addEventListener('focus',()=>{if(Date.now()-state.lastRefresh>60000)refresh()});
const footer=document.querySelector('.footer');if(footer)footer.textContent+=' · Build '+BUILD;
refresh();
})();