const FALLBACK={"asOf": "19/08/2026", "totals": {"total": 1432, "active": 1123, "drop": 309, "grad": 133}, "companies": [{"name": "Dương Huy", "total": 73, "active": 55, "drop": 18, "grad": 13}, {"name": "Hà Lầm", "total": 73, "active": 52, "drop": 21, "grad": 0}, {"name": "Hạ Long", "total": 128, "active": 106, "drop": 22, "grad": 58}, {"name": "Hòn Gai", "total": 134, "active": 121, "drop": 13, "grad": 0}, {"name": "Khe Chàm", "total": 208, "active": 155, "drop": 53, "grad": 0}, {"name": "Mạo Khê", "total": 64, "active": 52, "drop": 12, "grad": 0}, {"name": "Mông Dương", "total": 75, "active": 54, "drop": 21, "grad": 0}, {"name": "Nam Mẫu", "total": 116, "active": 92, "drop": 24, "grad": 0}, {"name": "Núi Béo", "total": 110, "active": 82, "drop": 28, "grad": 0}, {"name": "Quang Hanh", "total": 53, "active": 40, "drop": 13, "grad": 7}, {"name": "Sin Quyền", "total": 97, "active": 96, "drop": 1, "grad": 0}, {"name": "Thống Nhất", "total": 58, "active": 29, "drop": 29, "grad": 43}, {"name": "Uông Bí", "total": 47, "active": 42, "drop": 5, "grad": 0}, {"name": "Vàng Danh", "total": 166, "active": 139, "drop": 27, "grad": 0}, {"name": "Xây Lắp Mỏ", "total": 30, "active": 8, "drop": 22, "grad": 12}], "provinces": [{"name": "Quảng Ninh", "total": 463, "active": 386, "drop": 77}, {"name": "Lào Cai", "total": 110, "active": 101, "drop": 9}, {"name": "Tuyên Quang", "total": 63, "active": 46, "drop": 17}, {"name": "Thái Nguyên", "total": 30, "active": 23, "drop": 7}, {"name": "Hưng Yên", "total": 28, "active": 23, "drop": 5}, {"name": "Quảng Ngãi", "total": 28, "active": 11, "drop": 17}, {"name": "Lai Châu", "total": 27, "active": 20, "drop": 7}, {"name": "Ninh Bình", "total": 23, "active": 19, "drop": 4}, {"name": "Hải Phòng", "total": 22, "active": 17, "drop": 5}, {"name": "Lạng Sơn", "total": 19, "active": 13, "drop": 6}, {"name": "Thanh Hóa", "total": 19, "active": 17, "drop": 2}, {"name": "Điện Biên", "total": 16, "active": 12, "drop": 4}, {"name": "Cao Bằng", "total": 15, "active": 13, "drop": 2}, {"name": "Sơn La", "total": 15, "active": 11, "drop": 4}, {"name": "Nghệ An", "total": 12, "active": 10, "drop": 2}, {"name": "Phú Thọ", "total": 11, "active": 6, "drop": 5}]};
const CFG={sheetId:'14ceKz69_b4-lq70H_5zanSsiQjC1Og9jpFFrTFr2DYE',gid:'762412891',range:'A1:AW16000'};
const state={rows:[],filtered:[],dates:[],live:false};
const $=id=>document.getElementById(id);
const nf=new Intl.NumberFormat('vi-VN'); const pf=v=>new Intl.NumberFormat('vi-VN',{style:'percent',maximumFractionDigits:1}).format(v||0);
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function statusOf(v){const n=norm(v);if(!n||n==='dang thuc tap'||n==='dang tt')return'active';if(n==='bo'||n==='bo hoc'||n==='bo ttsx')return'dropped';if(n.includes('tot nghiep'))return'graduated';return'other'}
function setSync(cls,text){$('sync').className='sync '+cls;$('sync').querySelector('span:last-child').textContent=text}
function metrics(rows){let a=0,d=0,g=0,o=0;rows.forEach(r=>{if(r.status==='active')a++;else if(r.status==='dropped')d++;else if(r.status==='graduated')g++;else o++});const t=a+d;return{total:t,active:a,drop:d,grad:g,other:o,dropRate:t?d/t:0,activeRate:t?a/t:0}}
function fallbackMetrics(){const t=FALLBACK.totals;return{total:t.total,active:t.active,drop:t.drop,grad:t.grad,dropRate:t.drop/t.total,activeRate:t.active/t.total}}
function fillSelect(id,vals){const s=$(id),cur=s.value;s.innerHTML='<option value="">Tất cả</option>'+[...new Set(vals.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi')).map(v=>'<option>'+String(v).replace(/</g,'&lt;')+'</option>').join('');if([...s.options].some(o=>o.value===cur))s.value=cur}
function renderFallback(){renderKpis(fallbackMetrics());renderCompanyFallback();renderProvinceFallback();$('updated').textContent='Snapshot '+FALLBACK.asOf;$('quality').innerHTML='<div class="quality-empty">Kết nối dữ liệu trực tiếp để kiểm tra các trường hợp thiếu tỉnh, phân hiệu, đơn vị tuyển và công trường.</div>';['dExpected','dEntered','dScore','dSick','dLeave','dKld','dMissing'].forEach(id=>$(id).textContent='—');$('day').innerHTML='<option>Chưa có dữ liệu trực tiếp</option>';$('day').disabled=true;$('coverage').innerHTML='<div class="notice">Cần dữ liệu trực tiếp để tính tỷ lệ cập nhật.</div>';$('hotspots').innerHTML='<div class="notice">Cần dữ liệu trực tiếp để tính công trường cảnh báo.</div>';}
function renderKpis(m){$('kTotal').textContent=nf.format(m.total);$('kActive').textContent=nf.format(m.active);$('kDrop').textContent=nf.format(m.drop);$('kGrad').textContent=nf.format(m.grad);$('kDropRate').textContent=pf(m.dropRate);$('kDropRateSub').textContent=pf(m.dropRate);$('kActiveRate').textContent=pf(m.activeRate);$('kActivePct').textContent=pf(m.activeRate)}
function bars(el,arr,getVal,getName,getLabel,red=false,limit=15){const a=arr.slice(0,limit),mx=Math.max(1,...a.map(getVal));el.innerHTML=a.map(x=>`<div class="bar-row"><div class="bar-name" title="${getName(x)}">${getName(x)}</div><div class="track"><div class="fill ${red?'red':''}" style="width:${Math.max(1,getVal(x)/mx*100)}%"></div></div><div class="bar-value">${getLabel(x)}</div></div>`).join('')}
function renderCompanyFallback(){const arr=FALLBACK.companies.slice().sort((a,b)=>b.total-a.total);bars($('companyBars'),arr,x=>x.total,x=>x.name,x=>nf.format(x.total));const rate=FALLBACK.companies.map(x=>({...x,rate:x.total?x.drop/x.total:0})).sort((a,b)=>b.rate-a.rate);bars($('dropBars'),rate,x=>x.rate,x=>x.name,x=>pf(x.rate),true);$('companyTable').innerHTML=FALLBACK.companies.map(x=>`<tr><td>${x.name}</td><td>${nf.format(x.total)}</td><td>${nf.format(x.active)}</td><td class="${x.drop>=20?'danger':''}">${nf.format(x.drop)}</td><td class="${x.drop/x.total>=.3?'danger':''}">${pf(x.drop/x.total)}</td></tr>`).join('')}
function renderProvinceFallback(){const a=FALLBACK.provinces.slice().sort((a,b)=>b.total-a.total);bars($('provinceBars'),a,x=>x.total,x=>x.name,x=>nf.format(x.total),false,12)}
function parseTable(t){const h=t.cols.map((c,i)=>c.label||c.id||('C'+i));const rows=t.rows.map(row=>{const v=h.map((_,i)=>{const c=row.c?.[i];return c?.f??c?.v??''});const r={id:v[0],company:v[1],province:v[2],campus:v[3],recruitment:v[4],unit:v[5],statusRaw:v[6],status:statusOf(v[6]),daily:{}};for(let i=7;i<h.length;i++)r.daily[h[i]]=v[i];return r}).filter(r=>r.company);return{headers:h,rows}}
function loadLive(){return new Promise((resolve,reject)=>{const cb='__ttsx_'+Date.now();let done=false;const timer=setTimeout(()=>finish(new Error('Quá thời gian kết nối Google Sheets')),18000);function finish(err,data){if(done)return;done=true;clearTimeout(timer);delete window[cb];document.getElementById('sheet-loader')?.remove();err?reject(err):resolve(data)}window[cb]=resp=>{if(resp?.status!=='ok'||!resp.table)return finish(new Error(resp?.errors?.[0]?.detailed_message||'Google Sheets từ chối truy cập'));try{finish(null,parseTable(resp.table))}catch(e){finish(e)}};const s=document.createElement('script');s.id='sheet-loader';const tqx=encodeURIComponent('out:json;responseHandler:'+cb);s.src=`https://docs.google.com/spreadsheets/d/${CFG.sheetId}/gviz/tq?gid=${CFG.gid}&range=${encodeURIComponent(CFG.range)}&headers=1&tqx=${tqx}&_=${Date.now()}`;s.onerror=()=>finish(new Error('Không tải được endpoint Google Sheets'));document.head.appendChild(s)})}
function hydrate(){$('day').disabled=false;fillSelect('company',state.rows.map(r=>r.company));fillSelect('province',state.rows.map(r=>r.province));fillSelect('campus',state.rows.map(r=>r.campus));fillSelect('recruitment',state.rows.map(r=>r.recruitment));fillSelect('unit',state.rows.map(r=>r.unit));$('day').innerHTML=state.dates.map(d=>`<option>${d}</option>`).join('');const today=new Date().toLocaleDateString('vi-VN');if(state.dates.includes(today))$('day').value=today;else $('day').selectedIndex=Math.max(0,state.dates.length-1)}
function apply(){if(!state.live)return;const f={company:$('company').value,province:$('province').value,campus:$('campus').value,recruitment:$('recruitment').value,unit:$('unit').value,status:$('status').value};state.filtered=state.rows.filter(r=>Object.entries(f).every(([k,v])=>!v||r[k]===v));$('scope').textContent=state.filtered.length===state.rows.length?'Toàn bộ dữ liệu':nf.format(state.filtered.length)+' bản ghi trong phạm vi lọc';renderLive()}
function group(rows,key){const m=new Map;rows.forEach(r=>{const k=r[key]||'Chưa rõ';if(!m.has(k))m.set(k,[]);m.get(k).push(r)});return [...m.entries()]}
function renderLive(){const m=metrics(state.filtered);renderKpis(m);const cs=group(state.filtered,'company').map(([name,rows])=>({name,...metrics(rows)}));bars($('companyBars'),cs.sort((a,b)=>b.total-a.total),x=>x.total,x=>x.name,x=>nf.format(x.total));bars($('dropBars'),cs.sort((a,b)=>b.dropRate-a.dropRate),x=>x.dropRate,x=>x.name,x=>pf(x.dropRate),true);$('companyTable').innerHTML=cs.slice().sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(x=>`<tr><td>${x.name}</td><td>${nf.format(x.total)}</td><td>${nf.format(x.active)}</td><td class="${x.drop>=20?'danger':''}">${nf.format(x.drop)}</td><td class="${x.dropRate>=.3?'danger':''}">${pf(x.dropRate)}</td></tr>`).join('');const ps=group(state.filtered,'province').map(([name,rows])=>({name,...metrics(rows)})).sort((a,b)=>b.total-a.total);bars($('provinceBars'),ps,x=>x.total,x=>x.name,x=>nf.format(x.total),false,12);const unknownProvince=state.filtered.filter(r=>!r.province||norm(r.province).includes('chua ro')).length,unknownCampus=state.filtered.filter(r=>!r.campus).length,unknownRecruit=state.filtered.filter(r=>!r.recruitment).length,unknownUnit=state.filtered.filter(r=>!r.unit).length;$('quality').innerHTML=[[unknownProvince,'Chưa rõ tỉnh'],[unknownCampus,'Thiếu phân hiệu'],[unknownRecruit,'Thiếu đơn vị tuyển'],[unknownUnit,'Thiếu công trường']].map(([v,l])=>`<div class="q"><strong>${nf.format(v)}</strong><span>${l}</span></div>`).join('');renderDaily();renderHotspots()}
function classifyDay(v){if(typeof v==='number'&&Number.isFinite(v))return'score';const s=String(v??'').trim();if(!s)return'blank';if(Number.isFinite(Number(s.replace(',','.'))))return'score';if(s.toUpperCase()==='Ô')return'sick';if(s.toUpperCase()==='N')return'leave';if(s.toUpperCase()==='KLD')return'kld';return'other'}
function renderDaily(){if(!state.live)return;const day=$('day').value,rows=state.filtered.filter(r=>r.status==='active');let score=0,sick=0,leave=0,kld=0,other=0;rows.forEach(r=>{const t=classifyDay(r.daily[day]);if(t==='score')score++;else if(t==='sick')sick++;else if(t==='leave')leave++;else if(t==='kld')kld++;else if(t==='other')other++});const entered=score+sick+leave+kld+other,missing=Math.max(0,rows.length-entered);[['dExpected',rows.length],['dEntered',entered],['dScore',score],['dSick',sick],['dLeave',leave],['dKld',kld],['dMissing',missing]].forEach(([id,v])=>$(id).textContent=nf.format(v));const cov=group(rows,'company').map(([name,a])=>{const e=a.filter(r=>classifyDay(r.daily[day])!=='blank').length;return{name,rate:a.length?e/a.length:0}}).sort((a,b)=>b.rate-a.rate);bars($('coverage'),cov,x=>x.rate,x=>x.name,x=>pf(x.rate),false,15)}
function renderHotspots(){const drops=state.filtered.filter(r=>r.status==='dropped'&&r.unit);const hs=group(drops,'unit').map(([unit,rows])=>({unit,count:rows.length,companies:[...new Set(rows.map(r=>r.company))].join(', ')})).filter(x=>x.count>=3).sort((a,b)=>b.count-a.count);$('hotspots').innerHTML=hs.length?hs.slice(0,30).map(x=>`<div class="hot"><strong>${x.unit} · ${x.count} HS bỏ</strong><small>${x.companies}</small></div>`).join(''):'<div class="notice ok">Không có công trường nào đạt ngưỡng ≥3 HS bỏ trong phạm vi lọc.</div>'}
async function refresh(){setSync('', 'Đang kết nối dữ liệu');$('notice').className='notice';$('notice').textContent='Đang hiển thị số liệu dự phòng gần nhất trong khi kết nối Google Sheets.';try{const data=await loadLive();state.rows=data.rows;state.dates=data.headers.slice(7);state.live=true;hydrate();apply();setSync('ok','Dữ liệu trực tiếp');$('notice').className='notice ok';$('notice').textContent='Đã kết nối dữ liệu trực tiếp từ BC TTSX. Bộ lọc và số liệu đang tính theo dữ liệu hiện tại.';$('updated').textContent='Đồng bộ '+new Date().toLocaleString('vi-VN',{hour12:false})}catch(e){console.error(e);state.live=false;renderFallback();setSync('err','Đang dùng snapshot');$('notice').className='notice err';$('notice').textContent='Không kết nối được Google Sheets: '+e.message+'. Dashboard vẫn hiển thị snapshot '+FALLBACK.asOf+' thay vì màn hình trắng.'}}
['company','province','campus','recruitment','unit','status'].forEach(id=>$(id).addEventListener('change',apply));$('day').addEventListener('change',renderDaily);$('clear').addEventListener('click',()=>{['company','province','campus','recruitment','unit','status'].forEach(id=>$(id).value='');apply()});$('refresh').addEventListener('click',refresh);
renderFallback();refresh();