const FALLBACK={
  asOf:'19/08/2026',
  totals:{total:1432,active:1123,drop:309,grad:133},
  companies:[
    ['Dương Huy',73,55,18,13],['Hà Lầm',73,52,21,0],['Hạ Long',128,106,22,58],['Hòn Gai',134,121,13,0],
    ['Khe Chàm',208,155,53,0],['Mạo Khê',64,52,12,0],['Mông Dương',75,54,21,0],['Nam Mẫu',116,92,24,0],
    ['Núi Béo',110,82,28,0],['Quang Hanh',53,40,13,7],['Sin Quyền',97,96,1,0],['Thống Nhất',58,29,29,43],
    ['Uông Bí',47,42,5,0],['Vàng Danh',166,139,27,0],['Xây Lắp Mỏ',30,8,22,12]
  ].map(([name,total,active,drop,grad])=>({name,total,active,drop,grad})),
  provinces:[
    ['Quảng Ninh',463,386,77],['Lào Cai',110,101,9],['Tuyên Quang',63,46,17],['Thái Nguyên',30,23,7],
    ['Hưng Yên',28,23,5],['Quảng Ngãi',28,11,17],['Lai Châu',27,20,7],['Ninh Bình',23,19,4],
    ['Hải Phòng',22,17,5],['Lạng Sơn',19,13,6],['Thanh Hóa',19,17,2],['Điện Biên',16,12,4],
    ['Cao Bằng',15,13,2],['Sơn La',15,11,4],['Nghệ An',12,10,2],['Phú Thọ',11,6,5]
  ].map(([name,total,active,drop])=>({name,total,active,drop}))
};

const CFG={sheetId:'14ceKz69_b4-lq70H_5zanSsiQjC1Og9jpFFrTFr2DYE',gid:'762412891',sheet:'_WEB_DATA',range:'A1:AW2000',coreRange:'A1:G2000'};
const state={rows:[],scopeRows:[],dates:[],live:false,coreOnly:false};
const $=id=>document.getElementById(id);
const nf=new Intl.NumberFormat('vi-VN');
const pf=v=>new Intl.NumberFormat('vi-VN',{style:'percent',maximumFractionDigits:1}).format(v||0);
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function statusOf(v){const n=norm(v);if(!n||n==='dang thuc tap'||n==='dang tt')return'active';if(n==='bo'||n==='bo hoc'||n==='bo ttsx')return'dropped';if(n.includes('tot nghiep'))return'graduated';return'other'}
function setSync(cls,text){$('sync').className='sync '+cls;$('sync').querySelector('span:last-child').textContent=text}
function metrics(rows){let active=0,drop=0,grad=0,other=0;for(const r of rows){if(r.status==='active')active++;else if(r.status==='dropped')drop++;else if(r.status==='graduated')grad++;else other++}const total=active+drop;return{total,active,drop,grad,other,dropRate:total?drop/total:0,activeRate:total?active/total:0}}
function fallbackMetrics(){const t=FALLBACK.totals;return{...t,dropRate:t.drop/t.total,activeRate:t.active/t.total}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fillSelect(id,vals){const s=$(id),cur=s.value;const unique=[...new Set(vals.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'vi'));s.innerHTML='<option value="">Tất cả</option>'+unique.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');if([...s.options].some(o=>o.value===cur))s.value=cur}
function renderKpis(m){$('kTotal').textContent=nf.format(m.total);$('kActive').textContent=nf.format(m.active);$('kDrop').textContent=nf.format(m.drop);$('kGrad').textContent=nf.format(m.grad);$('kDropRate').textContent=pf(m.dropRate);$('kDropRateSub').textContent=pf(m.dropRate);$('kActiveRate').textContent=pf(m.activeRate);$('kActivePct').textContent=pf(m.activeRate)}
function countBars(el,arr,getVal,getName,getLabel,limit=15){const a=arr.slice(0,limit),mx=Math.max(1,...a.map(getVal));el.innerHTML=a.map(x=>{const val=getVal(x),name=getName(x);return `<div class="bar-row"><div class="bar-name" title="${escapeHtml(name)}">${escapeHtml(name)}</div><div class="track"><div class="fill" style="width:${val?Math.max(1,val/mx*100):0}%"></div></div><div class="bar-value">${getLabel(x)}</div></div>`}).join('')}
function rateBars(el,arr,limit=15){const a=arr.slice(0,limit);el.innerHTML=a.map(x=>{const pct=Math.max(0,Math.min(100,x.dropRate*100));const title=`${x.drop} HS bỏ / ${x.total} HS đi TTSX`;return `<div class="bar-row"><div class="bar-name" title="${escapeHtml(title)}">${escapeHtml(x.name)}</div><div class="track"><div class="fill red" style="width:${pct?Math.max(1,pct):0}%"></div></div><div class="bar-value" title="${escapeHtml(title)}">${pf(x.dropRate)}</div></div>`}).join('')}
function renderCompanyFallback(){const arr=FALLBACK.companies.slice().sort((a,b)=>b.total-a.total);countBars($('companyBars'),arr,x=>x.total,x=>x.name,x=>nf.format(x.total));const rates=FALLBACK.companies.map(x=>({...x,dropRate:x.total?x.drop/x.total:0})).sort((a,b)=>b.dropRate-a.dropRate);rateBars($('dropBars'),rates);$('companyTable').innerHTML=FALLBACK.companies.slice().sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${nf.format(x.total)}</td><td>${nf.format(x.active)}</td><td class="${x.drop>=20?'danger':''}">${nf.format(x.drop)}</td><td class="${x.drop/x.total>=.3?'danger':''}">${pf(x.drop/x.total)}</td></tr>`).join('')}
function renderProvinceFallback(){const a=FALLBACK.provinces.slice().sort((a,b)=>b.total-a.total);countBars($('provinceBars'),a,x=>x.total,x=>x.name,x=>nf.format(x.total),12)}
function renderFallback(){renderKpis(fallbackMetrics());renderCompanyFallback();renderProvinceFallback();$('scope').textContent='Toàn bộ dữ liệu · snapshot';$('updated').textContent='Snapshot '+FALLBACK.asOf;$('quality').innerHTML='<div class="quality-empty">Đang dùng snapshot. Cần kết nối dữ liệu trực tiếp để kiểm tra trường hợp thiếu thông tin.</div>';['dExpected','dEntered','dScore','dSick','dLeave','dKld','dMissing'].forEach(id=>$(id).textContent='—');$('day').innerHTML='<option>Chưa có dữ liệu trực tiếp</option>';$('day').disabled=true;$('coverage').innerHTML='<div class="notice">Cần dữ liệu trực tiếp để tính tỷ lệ cập nhật.</div>';$('hotspots').innerHTML='<div class="notice">Cần dữ liệu trực tiếp để tính công trường cảnh báo.</div>'}
function parseTable(t){const headers=t.cols.map((c,i)=>c.label||c.id||('C'+i));const rows=t.rows.map(row=>{const v=headers.map((_,i)=>{const c=row.c?.[i];return c?.f??c?.v??''});const r={id:v[0],company:v[1],province:v[2],campus:v[3],recruitment:v[4],unit:v[5],statusRaw:v[6],status:statusOf(v[6]),daily:{}};for(let i=7;i<headers.length;i++)r.daily[headers[i]]=v[i];return r}).filter(r=>r.company);return{headers,rows}}
function loadLive(range=CFG.range){return new Promise((resolve,reject)=>{const cb='__ttsx_'+Date.now()+'_'+Math.random().toString(36).slice(2);let done=false;const timer=setTimeout(()=>finish(new Error('Quá thời gian kết nối Google Sheets')),30000);function finish(err,data){if(done)return;done=true;clearTimeout(timer);delete window[cb];document.getElementById('sheet-loader')?.remove();err?reject(err):resolve(data)}window[cb]=resp=>{if(resp?.status!=='ok'||!resp.table)return finish(new Error(resp?.errors?.[0]?.detailed_message||'Google Sheets từ chối truy cập'));try{finish(null,parseTable(resp.table))}catch(e){finish(e)}};const s=document.createElement('script');s.id='sheet-loader';const tqx=encodeURIComponent('out:json;responseHandler:'+cb);s.src=`https://docs.google.com/spreadsheets/d/${CFG.sheetId}/gviz/tq?sheet=${encodeURIComponent(CFG.sheet)}&range=${encodeURIComponent(range)}&headers=1&tqx=${tqx}&_=${Date.now()}`;s.onerror=()=>finish(new Error('Không tải được endpoint Google Sheets'));document.head.appendChild(s)})}
function hydrate(){fillSelect('company',state.rows.map(r=>r.company));fillSelect('province',state.rows.map(r=>r.province));fillSelect('campus',state.rows.map(r=>r.campus));fillSelect('recruitment',state.rows.map(r=>r.recruitment));fillSelect('unit',state.rows.map(r=>r.unit));if(state.dates.length){$('day').disabled=false;$('day').innerHTML=state.dates.map(d=>`<option>${escapeHtml(d)}</option>`).join('');const today=new Date().toLocaleDateString('vi-VN');if(state.dates.includes(today))$('day').value=today;else $('day').selectedIndex=Math.max(0,state.dates.length-1)}else{$('day').innerHTML='<option>Chưa tải dữ liệu theo ngày</option>';$('day').disabled=true}}
function currentFilters(){return{company:$('company').value,province:$('province').value,campus:$('campus').value,recruitment:$('recruitment').value,unit:$('unit').value}}
function apply(){if(!state.live)return;const f=currentFilters();state.scopeRows=state.rows.filter(r=>Object.entries(f).every(([k,v])=>!v||r[k]===v));const m=metrics(state.scopeRows);$('scope').textContent=state.scopeRows.length===state.rows.length?'Toàn bộ dữ liệu':`${nf.format(state.scopeRows.length)} bản ghi · ${nf.format(m.total)} HS đi TTSX trong phạm vi lọc`;renderLive()}
function group(rows,key){const m=new Map;for(const r of rows){const k=r[key]||'Chưa rõ';if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return[...m.entries()]}
function renderLive(){const baseRows=state.scopeRows;const m=metrics(baseRows);renderKpis(m);const companies=group(baseRows,'company').map(([name,rows])=>({name,...metrics(rows)}));countBars($('companyBars'),companies.slice().sort((a,b)=>b.total-a.total),x=>x.total,x=>x.name,x=>nf.format(x.total));rateBars($('dropBars'),companies.slice().sort((a,b)=>b.dropRate-a.dropRate));$('companyTable').innerHTML=companies.slice().sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${nf.format(x.total)}</td><td>${nf.format(x.active)}</td><td class="${x.drop>=20?'danger':''}">${nf.format(x.drop)}</td><td class="${x.dropRate>=.3?'danger':''}" title="${x.drop} / ${x.total}">${pf(x.dropRate)}</td></tr>`).join('');const provinces=group(baseRows,'province').map(([name,rows])=>({name,...metrics(rows)})).sort((a,b)=>b.total-a.total);countBars($('provinceBars'),provinces,x=>x.total,x=>x.name,x=>nf.format(x.total),12);const unknownProvince=baseRows.filter(r=>!r.province||norm(r.province).includes('chua ro')).length,unknownCampus=baseRows.filter(r=>!r.campus).length,unknownRecruit=baseRows.filter(r=>!r.recruitment).length,unknownUnit=baseRows.filter(r=>!r.unit).length;$('quality').innerHTML=[[unknownProvince,'Chưa rõ tỉnh'],[unknownCampus,'Thiếu phân hiệu'],[unknownRecruit,'Thiếu đơn vị tuyển'],[unknownUnit,'Thiếu công trường']].map(([v,l])=>`<div class="q"><strong>${nf.format(v)}</strong><span>${l}</span></div>`).join('');renderDaily();renderHotspots()}
function classifyDay(v){if(typeof v==='number'&&Number.isFinite(v))return'score';const s=String(v??'').trim();if(!s)return'blank';if(Number.isFinite(Number(s.replace(',','.'))))return'score';if(s.toUpperCase()==='Ô')return'sick';if(s.toUpperCase()==='N')return'leave';if(s.toUpperCase()==='KLD')return'kld';return'other'}
function renderDaily(){if(!state.live)return;if(state.coreOnly||!state.dates.length){['dExpected','dEntered','dScore','dSick','dLeave','dKld','dMissing'].forEach(id=>$(id).textContent='—');$('coverage').innerHTML='<div class="notice">Bộ lọc và thống kê đã hoạt động. Dải dữ liệu theo ngày chưa tải được.</div>';return}const day=$('day').value,rows=state.scopeRows.filter(r=>r.status==='active');let score=0,sick=0,leave=0,kld=0,other=0;for(const r of rows){const t=classifyDay(r.daily[day]);if(t==='score')score++;else if(t==='sick')sick++;else if(t==='leave')leave++;else if(t==='kld')kld++;else if(t==='other')other++}const entered=score+sick+leave+kld+other,missing=Math.max(0,rows.length-entered);[['dExpected',rows.length],['dEntered',entered],['dScore',score],['dSick',sick],['dLeave',leave],['dKld',kld],['dMissing',missing]].forEach(([id,v])=>$(id).textContent=nf.format(v));const cov=group(rows,'company').map(([name,a])=>{const enteredCount=a.filter(r=>classifyDay(r.daily[day])!=='blank').length;return{name,rate:a.length?enteredCount/a.length:0}}).sort((a,b)=>b.rate-a.rate);$('coverage').innerHTML=cov.slice(0,15).map(x=>`<div class="bar-row"><div class="bar-name">${escapeHtml(x.name)}</div><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,x.rate*100))}%"></div></div><div class="bar-value">${pf(x.rate)}</div></div>`).join('')}
function renderHotspots(){const drops=state.scopeRows.filter(r=>r.status==='dropped'&&r.unit&&r.company);const pairMap=new Map;for(const r of drops){const company=String(r.company).trim(),unit=String(r.unit).trim(),key=norm(company)+'\u0000'+norm(unit);if(!pairMap.has(key))pairMap.set(key,{company,unit,count:0});pairMap.get(key).count++}const pairs=[...pairMap.values()].filter(x=>x.count>=3),companyMap=new Map;for(const x of pairs){const key=norm(x.company);if(!companyMap.has(key))companyMap.set(key,{company:x.company,total:0,units:[]});const g=companyMap.get(key);g.total+=x.count;g.units.push({unit:x.unit,count:x.count})}const groups=[...companyMap.values()].map(g=>({...g,units:g.units.sort((a,b)=>b.count-a.count||a.unit.localeCompare(b.unit,'vi'))})).sort((a,b)=>b.total-a.total||a.company.localeCompare(b.company,'vi'));$('hotspots').innerHTML=groups.length?groups.map(g=>`<div class="hot-company-row"><div class="hot-company-box"><strong>${escapeHtml(g.company)}</strong><span>${nf.format(g.total)} HS bỏ tại ${g.units.length} công trường</span></div><div class="hot-unit-list">${g.units.map(u=>`<div class="hot-unit"><span>${escapeHtml(u.unit)}</span><b>${nf.format(u.count)} HS bỏ</b></div>`).join('')}</div></div>`).join(''):'<div class="notice ok">Không có công trường nào đạt ngưỡng ≥3 HS bỏ trong phạm vi lọc.</div>'}
async function refresh(){setSync('','Đang kết nối dữ liệu');$('notice').className='notice';$('notice').textContent='Đang kết nối Google Sheets và nạp bộ lọc.';try{let data,coreOnly=false;try{data=await loadLive(CFG.range)}catch(fullErr){console.warn('Full feed failed, retry core feed',fullErr);data=await loadLive(CFG.coreRange);coreOnly=true}state.rows=data.rows;state.scopeRows=data.rows;state.dates=coreOnly?[]:data.headers.slice(7);state.live=true;state.coreOnly=coreOnly;hydrate();apply();setSync('ok',coreOnly?'Dữ liệu trực tiếp · lõi':'Dữ liệu trực tiếp');$('notice').className='notice ok';$('notice').textContent=coreOnly?'Đã kết nối dữ liệu trực tiếp cho bộ lọc, KPI và cảnh báo công trường. Phần theo dõi ngày chưa tải được.':'Đã kết nối dữ liệu trực tiếp từ BC TTSX. Tất cả khối đang dùng cùng một phạm vi dữ liệu.';$('updated').textContent='Đồng bộ '+new Date().toLocaleString('vi-VN',{hour12:false})}catch(e){console.error(e);state.live=false;state.coreOnly=false;renderFallback();setSync('err','Đang dùng snapshot');$('notice').className='notice err';$('notice').textContent='Không kết nối được Google Sheets: '+e.message+'. Dashboard đang dùng snapshot '+FALLBACK.asOf+'.'}}
['company','province','campus','recruitment','unit'].forEach(id=>$(id).addEventListener('change',apply));$('day').addEventListener('change',renderDaily);$('clear').addEventListener('click',()=>{['company','province','campus','recruitment','unit'].forEach(id=>$(id).value='');apply()});$('refresh').addEventListener('click',refresh);renderFallback();refresh();